name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    name: 'Publish on the development server'
    steps:
    
      - uses: arwynfr/actions-docker-context@v2
        with:
          docker_host: 'ssh://eduempire@eduempire.de'
          context_name: 'remote'
          ssh_key: ${{ secrets.SSH_KEY }}

      - run: |
          docker context use remote
          docker context ls
          docker compose -f production-compose.yaml up -d --build
