name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    name: 'Publish on the development server'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up docker context over SSH authentication
        uses: amirmarmul/docker-context-ssh-action@v1
        with:
          ssh-host: eduempire.de
          ssh-username: eduempire
          ssh-private-key: ${{ secrets.SSH_KEY }}
          context-use: true

      - name: Add remote host to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan eduempire.de >> ~/.ssh/known_hosts

      - run: |
          docker context use remote
          docker context ls
          docker compose -f production-compose.yaml up -d --build
